export const week_days = [
  { label: "א", value: "1" },
  { label: "ב", value: "2" },
  { label: "ג", value: "3" },
  { label: "ד", value: "4" },
  { label: "ה", value: "5" },
  { label: "ו", value: "6" },
  { label: "ש", value: "7" },
];

export const rep_options = [
  { label: "יומי", value: "daily" },
  { label: "שבועי", value: "weekly" },
  { label: "חדשי", value: "monthlyHe" },
  { label: "שנתי", value: "yearlyHe" },
  { label: "חד פעמי", value: "singleHe" },
  { label: "שבת", value: "shabatot" },
  { label: "חגים", value: "chagim" },
];

export const time_modes = [
  { label: "זמן מקומי", value: "localTime" },
  { label: "לפני שקיעה", value: "preSunset" },
  { label: "אחרי שקיעה", value: "postSunset" },
];

export const hebrewMonths = [
  { label: "תשרי", value: "1" },
  { label: "חשוון", value: "2" },
  { label: "כסלו", value: "3" },
  { label: "טבת", value: "4" },
  { label: "שבט", value: "5" },
  { label: "אדר א", value: "6" },
  { label: "אדר ב", value: "7" },
  { label: "ניסן", value: "8" },
  { label: "אייר", value: "9" },
  { label: "סיון", value: "10" },
  { label: "תמוז", value: "11" },
  { label: "אב", value: "12" },
  { label: "אלול", value: "13" },
];

export const hebrewMonthDays = [
  { label: "א", value: "1" },
  { label: "ב", value: "2" },
  { label: "ג", value: "3" },
  { label: "ד", value: "4" },
  { label: "ה", value: "5" },
  { label: "ו", value: "6" },
  { label: "ז", value: "7" },
  { label: "ח", value: "8" },
  { label: "ט", value: "9" },
  { label: "י", value: "10" },
  { label: "יא", value: "11" },
  { label: "יב", value: "12" },
  { label: "יג", value: "13" },
  { label: "יד", value: "14" },
  { label: "טו", value: "15" },
  { label: "טז", value: "16" },
  { label: "יז", value: "17" },
  { label: "יח", value: "18" },
  { label: "יט", value: "19" },
  { label: "כ", value: "20" },
  { label: "כא", value: "21" },
  { label: "כב", value: "22" },
  { label: "כג", value: "23" },
  { label: "כד", value: "24" },
  { label: "כה", value: "25" },
  { label: "כו", value: "26" },
  { label: "כז", value: "27" },
  { label: "כח", value: "28" },
  { label: "כט", value: "29" },
  { label: "ל", value: "30" },
];

export const hebrewYears = [
  { label: "תשפד", value: "5784" },
  { label: "תשפה", value: "5785" },
  { label: "תשפו", value: "5786" },
  { label: "תשפז", value: "5787" },
  { label: "תשפח", value: "5788" },
  { label: "תשפט", value: "5789" },
  { label: "תשצ", value: "5790" },
  { label: "תשצא", value: "5791" },
  { label: "תשצב", value: "5792" },
  { label: "תשצג", value: "5793" },
  { label: "תשצד", value: "5794" },
  { label: "תשצה", value: "5795" },
  { label: "תשצו", value: "5796" },
  { label: "תשצז", value: "5797" },
  { label: "תשצח", value: "5798" },
  { label: "תשצט", value: "5799" },
  { label: "תתא", value: "5800" },
];
